# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_tx_f-Cfz3k35iqT2jujIdTPqhw6Mtp
"""

# Todo List Manager using Python Lists

tasks = []
completed_tasks = []
priority = []
date = []

def add_task():
    task = input("Enter a new task: ")
    priority_input = input("Enter task priority (1 = Low, 2 = Medium, 3 = High): ")
    date_input = input("Enter task date (MM/DD/YYYY): ")

    # Store all information in the task dictionary
    tasks.append({
        "task": task,
        "completed": False,
        "priority": int(priority_input),
        "date": date_input
    })

    print(f"Task '{task}' added on {date_input} with a {priority_input} priority level")

def view_tasks():
    if not tasks:
        print("No tasks in the list!")
        return

    print("\n--- Tasks ---")
    for i, task in enumerate(tasks, 1):
        status = "✓" if task["completed"] else " "
        priority_name = "Low" if task["priority"] == 1 else "Medium" if task["priority"] == 2 else "High"
        print(f"{i}. [{status}] {task['task']} - Priority: {priority_name}, Date: {task['date']}")

def mark_completed():
    view_tasks()
    try:
        task_num = int(input("Enter task number to mark complete: ")) - 1
        if 0 <= task_num < len(tasks):
            tasks[task_num]["completed"] = True
            print("Task marked as completed!")
        else:
            print("Invalid task number!")
    except ValueError:
        print("Please enter a valid number!")

def delete_task():
    view_tasks()
    try:
        task_num = int(input("Enter task number to delete: ")) - 1
        if 0 <= task_num < len(tasks):
            removed = tasks.pop(task_num)
            print(f"Task '{removed['task']}' deleted!")
        else:
            print("Invalid task number!")
    except ValueError:
        print("Please enter a valid number!")

def sort_task_by_priority_and_date():
    view_tasks()
    sort_by_input = input("Press 1 to sort by priority level \nPress 2 to sort by date: ")

    global tasks

    if sort_by_input == "1":
        tasks = sorted(tasks, key=lambda x: -x["priority"])
        print("Tasks sorted by priority (High to Low)")

    elif sort_by_input == "2":
        tasks = sorted(tasks, key=lambda x: x["date"])
        print("Tasks sorted by date (earliest first)")

    else:
        print("Invalid choice!")
        return

    view_tasks()

def search_task():
    search_term = input("Enter search term: ")
    search_term = search_term.lower()
    matching_tasks = []

    for task in tasks:
      task_text = task['task'].lower()
      if search_term in task_text:
        matching_tasks.append(task)

    if len(matching_tasks) > 0:
      print("\nSearch Results:")
      for i in range(len(matching_tasks)):
        task = matching_tasks[i]
        if task["completed"]:
          status = '✓'
        else:
          status = " "

        print(f"{i+1}. [{status}] {task['task']}")

    else:
      print('No Search results')

def main_menu():
    while True:
        print("\n==== Todo List Manager ====")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Mark Task Complete")
        print("4. Delete Task")
        print("5. Sort Tasks")
        print("6. Search Tasks")
        print("7. Quit")

        choice = input("Enter your choice (1-7): ")

        if choice == "1":
            add_task()
        elif choice == "2":
            view_tasks()
        elif choice == "3":
            mark_completed()
        elif choice == "4":
            delete_task()
        elif choice == "5":
            sort_task_by_priority_and_date()
        elif choice == "6":
            search_task()
        elif choice == "7":
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main_menu()

()